name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: yarn install
        working-directory: ./

      - name: Run Backend Linter
        run: yarn lint
        working-directory: ./

      - name: Run Backend Prettier Check
        run: yarn prettier --check .
        working-directory: ./
