name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for Project
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Project Dependencies
        run: yarn install
        working-directory: ./

      - name: Run Project Linter
        run: yarn lint
        working-directory: ./

      - name: Run Project Prettier Check
        run: yarn prettier --check .
        working-directory: ./
